### ISSUE TITLE
Einbindung in NodeRed 

### ISSUE THREAD

**Issue by Maze77** [danisahni/node-red-contrib-solaredge-optimizers#1]
Hallo,
ich versuche den Node mit dem InfluxDB Node zu verbinden.

Leider funktioniert hier etwas nicht und ich habe bisher den Fehler nicht finden können.

Es sieht so aus, alsob der Solaredge Node läuft und ich einige Einträge generiert (msg.payload existiert mit 4704 Einträgen].

Aber die Daten bekomme ich nicht in die InfluxDB mit dem erwähnten Node.
Gibt es hier spezielle Einstellungen? 
- Token, Organization und Bucket sind definiert
-  Measurement ist gleich gesetzt mit der Measurement definition in diesem SolarEdge Node.

Welche Time Precision sollte gewählt werden? 1s, oder 1 Nanosekunde? Keiner der Versuche hat geklappt.

Die Fehlermeldung ist folgende:
"HttpError: unable to parse 'optimizers,fields=[object Object],measurement=optimizers,tags=[object Object],timestamp=1710461700000 measurement="optimizers",timestamp=1710460800000 1710529697253161542': invalid boolean"
Eine Rückmeldung wäre klasse.

Gruß
Maze

**Comment by Maze77** [comment]
Solution:

Man muss die "influx batch" verwenden und die Zeiteinstellung auf "ms" einstellen. 

Dann klappt alles 1A!

**Comment by danisahni** [comment]
Freut mich, dass es nun klappt. In den Examples ist ein Beispiel für die direkte Verwendung mit InfluxDB. Damit es in Zukunft klarer ist, habe ich die Readme ein wenig angepasst und auf den Beispiel-Flow verlinkt.

**Comment by Maze77** [comment]
Ein Problem habe ich noch und zwar mit den Timezones.

Bei mir laufen sowohl der Grafana, InfluxDB und auch NodeRed Docker auf TZ = Europe/Berlin.

Aber irgendwie landen die Daten in InfluxDB in UTC und nicht in der angegebenen TZ. 

Wenn ich in Nodered debugge, so stimmen die Daten im Array, welches übergeben wird, noch mit Solaredge überein. Aber in Influx habe ich dann einen Offset von +1h.

Wie hast du das gelöst?

Gruß
Maze

**Comment by danisahni** [comment]
Ich denke, meine InfluxDB läuft in UTC. Aber damit man etwas flexibler ist, habe ich dem Node eine neue Option hinzugefügt: 
Unter Time Zone Settings kannst du einstellen, ob die Daten in lokaler Zeit oder UTC ausgegeben werden sollen. Wenn du also auf Local umstellst, sollte der Offset weg sein.
Die neue Version ist v.0.3.0. Manchmal dauert es etwas (30-60 Minuten), bis Node-Red ein Update anzeigt.

Falls es nicht wie gewünscht funktioniert, gerne nochmal melden. Mit den Time Zones tue ich mich immer etwas schwer, deswegen speicher ich gleich alles in UTC ab ;).

**Comment by Maze77** [comment]
Danke schonmal, aber ich bin nicht so tief in der Materie und mir ist nicht ganz klar wo ich das hinterlegen kann.

Ich hab die klassische TZ Variable auf Europe/Berlin stehen.
In dem "Original Python" Skript, welches Dir als Vorlage gedient hat, rechnen sie es wie folgt um:

date = pytz.timezone('Europe/Berlin').localize(date).astimezone(pytz.utc)

kA, wo das bei Dir in den Code dann rein müsste. Wäre natürlich Klasse, wenn es so einfach ginge. Ansonsten müsste ich meine Influx auf UTC umstellen und das halt dann bei allen anderen Daten bedenken ;) (Ist noch recht jungfräulich, ginge also). 


Gruß
Maze

**Comment by danisahni** [comment]
Am Code brauchst du nichts ändern: Schau mal in die Einstellungen des Nodes rein, dort sollte es in Version v0.3.0 einen neuen Input geben:
![image](https://github.com/danisahni/node-red-contrib-solaredge-optimizers/assets/51887375/a73bae40-7fa7-4b79-9e2f-e44ee5561fe6)

**Comment by Maze77** [comment]
Danke, seltsamerweise sehe ich das drop down noch nicht. 
Gleich nochmal den NodeRed Docker restarten.

**Comment by Maze77** [comment]
Top!

Scheint gepasst zu haben.

**Comment by danisahni** [comment]
Super, dann schließe ich hier wieder.

**Comment by Maze77** [comment]
Danke und schönes Wochenende!
